### ISSUE TITLE
Error on GET Request to taco subdomain

### ISSUE THREAD

**Issue by johnbonesnj** [maxogden/taco#12]
While I know that taco runs the git http service, out of curiosity I ran ```curl taco.mydomain.com``` and I get a nginx 502 error when I check taco logs this is what I get:

```
Sun, 25 May 2014 03:58:56 GMT taco Host.setup opening nginx conf /etc/nginx/nginx.conf
Sun, 25 May 2014 03:58:56 GMT taco Host.setup nginx conf already configured correctly
Sun, 25 May 2014 03:58:56 GMT taco Host.setup nginx is running
Sun, 25 May 2014 03:58:56 GMT taco Host.setup reloading nginx configuration...
listening on 8080
Sun, 25 May 2014 04:02:10 GMT taco Host.handle XXX.XXX.XXX.XXX - GET - /
Sun, 25 May 2014 04:02:10 GMT taco Host.handle no user/pass set, accepting request

/usr/local/lib/node_modules/taco/index.js:147
      debug('Host.handle onService ' + service.action + ' err: ' + err)
                                              ^
TypeError: Cannot read property 'action' of undefined
    at Backend.onService (/usr/local/lib/node_modules/taco/index.js:147:47)
    at Backend.EventEmitter.emit (events.js:117:20)
    at /usr/local/lib/node_modules/taco/node_modules/git-http-backend/index.js:64:45
    at process._tickCallback (node.js:419:13)
Sun, 25 May 2014 04:02:11 GMT taco Host.setup opening nginx conf /etc/nginx/nginx.conf
Sun, 25 May 2014 04:02:11 GMT taco Host.setup nginx conf already configured correctly
Sun, 25 May 2014 04:02:11 GMT taco Host.setup nginx is running
Sun, 25 May 2014 04:02:11 GMT taco Host.setup reloading nginx configuration...
listening on 8080
```

**Comment by maxogden** [comment]
sorry about that! closing this now as taco is being rewritten with a new design that avoids git
